[package]
name = "ray_tracing_in_one_weekend"
version = "1.0.0"
authors = ["HiraokaTakuya <hiraoka64@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
